# GET https://nc-games-9h15.onrender.com/api HTTP/1.1
GET https://nc-games-9h15.onrender.com/api/reviews HTTP/1.1
# GET https://nc-games-9h15.onrender.com/api/reviews/21 HTTP/1.1
# GET https://nc-games-9h15.onrender.com/api/reviews/21/comments HTTP/1.1
# GET https://nc-games-9h15.onrender.com/api/reviews/18/ HTTP/1.1

# PATCH https://nc-games-9h15.onrender.com/api/reviews/18/ HTTP/1.1
# Content-Type: application/json

# {
#     "incVotes": 1
# }

# PATCH https://nc-games-9h15.onrender.com/api/comments/2/ HTTP/1.1
# Content-Type: application/json

# {
#     "inc_votes": 1
# }

# POST https://nc-games-9h15.onrender.com/api/reviews/18/comments HTTP/1.1
# Content-Type: application/json

# {
#     "username": "weegembump",
#     "body": "another test comment 2"
# }

# GET https://nc-games-9h15.onrender.com/api/users HTTP/1.1

GET https://nc-games-9h15.onrender.com/api/reviews?category=strategy&order=DESC&sort_by=votes HTTP/1.1
